version: "3"
services:
  app:
    build: .
    image: urban-topology
    depends_on:
      - database
    ports:
      - "81:3000"
    volumes:
      - public:/var/app/public
    environment:
      RAILS_MASTER_KEY:

  database:
    image: postgres:15.0
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  db_data:
  public: